export default{
  development:{
    ARMORY_SERVICE_BASE:'http://localhost',
    ARMORY_SERVICE_PORT:9912,
    AUTH_SERVICE_BASE:'http://localhost',
    AUTH_SERVICE_PORT:9661
  },
  testing:{
    ARMORY_SERVICE_BASE:'http://localhost',
    ARMORY_SERVICE_PORT:9912,
    AUTH_SERVICE_BASE:'http://localhost',
    AUTH_SERVICE_PORT:9661
  },
  production:{
    ARMORY_SERVICE_BASE:'https://api.outlawdesigns.io',
    ARMORY_SERVICE_PORT:8420,
    AUTH_SERVICE_BASE:'https://api.outlawdesigns.io',
    AUTH_SERVICE_PORT:9661
  }
}
